/**
 * Material Design 3 (Material You) Semantic Color Tokens
 * Supports dynamic monet palettes: Forest Teal, Deep Violet, Ocean Blue, Amber Sunset
 */

export type PaletteName = 'forest-teal' | 'deep-violet' | 'ocean-blue' | 'amber-sunset';

export interface M3ColorScheme {
  name: string;
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string; // Used for Freeze Days / Jolly criogenici
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  error: string; // Used for Penalties and Debt
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
}

export const PALETTES: Record<PaletteName, { light: M3ColorScheme; dark: M3ColorScheme }> = {
  'forest-teal': {
    light: {
      name: 'Forest Teal (Light)',
      primary: '#006A60',
      onPrimary: '#FFFFFF',
      primaryContainer: '#73F8E7',
      onPrimaryContainer: '#00201C',
      secondary: '#4A635F',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#CCE8E2',
      onSecondaryContainer: '#05201C',
      tertiary: '#456179',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#CCE5FF',
      onTertiaryContainer: '#001D32',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      background: '#F4FAF8',
      onBackground: '#161D1B',
      surface: '#F4FAF8',
      onSurface: '#161D1B',
      surfaceVariant: '#DAE5E1',
      onSurfaceVariant: '#3F4946',
      outline: '#6F7976',
      outlineVariant: '#BEC9C5',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#EEF5F3',
      surfaceContainer: '#E8F0EE',
      surfaceContainerHigh: '#E2EAE8',
      surfaceContainerHighest: '#DCE4E2',
    },
    dark: {
      name: 'Forest Teal (Dark)',
      primary: '#53DBCB',
      onPrimary: '#003731',
      primaryContainer: '#004F48',
      onPrimaryContainer: '#73F8E7',
      secondary: '#B1CCC6',
      onSecondary: '#1C3531',
      secondaryContainer: '#334B47',
      onSecondaryContainer: '#CCE8E2',
      tertiary: '#ADC9E6',
      onTertiary: '#143349',
      tertiaryContainer: '#2D4A60',
      onTertiaryContainer: '#CCE5FF',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      background: '#0E1514',
      onBackground: '#DCE4E2',
      surface: '#0E1514',
      onSurface: '#DCE4E2',
      surfaceVariant: '#3F4946',
      onSurfaceVariant: '#BEC9C5',
      outline: '#899390',
      outlineVariant: '#3F4946',
      surfaceContainerLowest: '#090F0E',
      surfaceContainerLow: '#161D1B',
      surfaceContainer: '#1A2120',
      surfaceContainerHigh: '#252C2A',
      surfaceContainerHighest: '#2F3635',
    },
  },

  'deep-violet': {
    light: {
      name: 'Deep Violet (Light)',
      primary: '#6750A4',
      onPrimary: '#FFFFFF',
      primaryContainer: '#EADDFF',
      onPrimaryContainer: '#21005D',
      secondary: '#625B71',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#E8DEF8',
      onSecondaryContainer: '#1D192B',
      tertiary: '#7D5260',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#FFD8E4',
      onTertiaryContainer: '#31111D',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      background: '#FEF7FF',
      onBackground: '#1D1B20',
      surface: '#FEF7FF',
      onSurface: '#1D1B20',
      surfaceVariant: '#E7E0EC',
      onSurfaceVariant: '#49454F',
      outline: '#79747E',
      outlineVariant: '#CAC4D0',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F7F2FA',
      surfaceContainer: '#F3EDF7',
      surfaceContainerHigh: '#ECE6F0',
      surfaceContainerHighest: '#E6E0E9',
    },
    dark: {
      name: 'Deep Violet (Dark)',
      primary: '#D0BCFF',
      onPrimary: '#381E72',
      primaryContainer: '#4F378B',
      onPrimaryContainer: '#EADDFF',
      secondary: '#CCC2DC',
      onSecondary: '#332D41',
      secondaryContainer: '#4A4458',
      onSecondaryContainer: '#E8DEF8',
      tertiary: '#EFB8C8',
      onTertiary: '#492532',
      tertiaryContainer: '#633B48',
      onTertiaryContainer: '#FFD8E4',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      background: '#141218',
      onBackground: '#E6E0E9',
      surface: '#141218',
      onSurface: '#E6E0E9',
      surfaceVariant: '#49454F',
      onSurfaceVariant: '#CAC4D0',
      outline: '#938F99',
      outlineVariant: '#49454F',
      surfaceContainerLowest: '#0F0D13',
      surfaceContainerLow: '#1D1B20',
      surfaceContainer: '#211F26',
      surfaceContainerHigh: '#2B2930',
      surfaceContainerHighest: '#36343B',
    },
  },

  'ocean-blue': {
    light: {
      name: 'Ocean Blue (Light)',
      primary: '#006399',
      onPrimary: '#FFFFFF',
      primaryContainer: '#CDE5FF',
      onPrimaryContainer: '#001D32',
      secondary: '#51606F',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#D5E4F6',
      onSecondaryContainer: '#0E1D2A',
      tertiary: '#69577D',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#F1DAFF',
      onTertiaryContainer: '#241536',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      background: '#F8F9FF',
      onBackground: '#191C20',
      surface: '#F8F9FF',
      onSurface: '#191C20',
      surfaceVariant: '#DEE3EB',
      onSurfaceVariant: '#42474E',
      outline: '#72777F',
      outlineVariant: '#C2C7CF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F2F3FA',
      surfaceContainer: '#ECEEF4',
      surfaceContainerHigh: '#E6E8EE',
      surfaceContainerHighest: '#E0E2E8',
    },
    dark: {
      name: 'Ocean Blue (Dark)',
      primary: '#95CCFF',
      onPrimary: '#003353',
      primaryContainer: '#004A75',
      onPrimaryContainer: '#CDE5FF',
      secondary: '#B9C8DA',
      onSecondary: '#233240',
      secondaryContainer: '#3A4857',
      onSecondaryContainer: '#D5E4F6',
      tertiary: '#D4BEE6',
      onTertiary: '#3A2A4C',
      tertiaryContainer: '#514064',
      onTertiaryContainer: '#F1DAFF',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      background: '#111418',
      onBackground: '#E1E2E8',
      surface: '#111418',
      onSurface: '#E1E2E8',
      surfaceVariant: '#42474E',
      onSurfaceVariant: '#C2C7CF',
      outline: '#8C9199',
      outlineVariant: '#42474E',
      surfaceContainerLowest: '#0C0F12',
      surfaceContainerLow: '#191C20',
      surfaceContainer: '#1D2024',
      surfaceContainerHigh: '#272A2F',
      surfaceContainerHighest: '#32353A',
    },
  },

  'amber-sunset': {
    light: {
      name: 'Amber Sunset (Light)',
      primary: '#8A5100',
      onPrimary: '#FFFFFF',
      primaryContainer: '#FFDCBE',
      onPrimaryContainer: '#2D1600',
      secondary: '#735943',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#FFDCC1',
      onSecondaryContainer: '#2A1706',
      tertiary: '#5A6237',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#DEE7B0',
      onTertiaryContainer: '#171E00',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      background: '#FFF8F4',
      onBackground: '#211A14',
      surface: '#FFF8F4',
      onSurface: '#211A14',
      surfaceVariant: '#F3DFD1',
      onSurfaceVariant: '#51443B',
      outline: '#84746A',
      outlineVariant: '#D6C3B6',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#FCF1EA',
      surfaceContainer: '#F6EBE4',
      surfaceContainerHigh: '#F0E6DE',
      surfaceContainerHighest: '#EAE0D8',
    },
    dark: {
      name: 'Amber Sunset (Dark)',
      primary: '#FFB870',
      onPrimary: '#4A2800',
      primaryContainer: '#693C00',
      onPrimaryContainer: '#FFDCBE',
      secondary: '#E2C0A5',
      onSecondary: '#402C19',
      secondaryContainer: '#59422D',
      onSecondaryContainer: '#FFDCC1',
      tertiary: '#C2CB96',
      onTertiary: '#2C340D',
      tertiaryContainer: '#424B21',
      onTertiaryContainer: '#DEE7B0',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      background: '#19120C',
      onBackground: '#EAE0D8',
      surface: '#19120C',
      onSurface: '#EAE0D8',
      surfaceVariant: '#51443B',
      onSurfaceVariant: '#D6C3B6',
      outline: '#9F8D83',
      outlineVariant: '#51443B',
      surfaceContainerLowest: '#130D08',
      surfaceContainerLow: '#211A14',
      surfaceContainer: '#261E18',
      surfaceContainerHigh: '#312822',
      surfaceContainerHighest: '#3C332C',
    },
  },
};
